name: CentralCity
main: com.jaoafa.CentralCity.Main
version: ${project.version}
description: CentralCity
author: mine_book000
database: true
api-version: 1.18
softdepend:
  - WorldEdit
  - WorldGuard
commands:
  centralcity:
    description: 中央市関連の作業を行います。
    usage: |
      /centralcity: 中央市関連の作業を行います。
    permission: centralcity.centralcity