name: ChuoCity
main: com.jaoafa.ChuoCity.Main
version: ${project.version}
description: ChuoCity
author: mine_book000
database: true
api-version: 1.18
softdepend:
  - WorldEdit
  - WorldGuard
commands:
  chuocity:
    description: 中央市関連の作業を行います。
    usage: |
      /chuocity: 中央市関連の作業を行います。
    permission: chuocity.chuocity