name: Bakushinchi
main: com.jaoafa.Bakushinchi.Main
version: ${project.version}
description: Bakushinchi
author: mine_book000
database: true
api-version: 1.18
softdepend:
  - WorldEdit
  - WorldGuard
commands:
  bakushinchi:
    description: 爆新地関連の作業を行います。
    usage: |
      /bakushinchi: 爆新地関連の作業を行います。
    permission: bakushinchi.bakushinchi